#!/usr/bin/env pwsh
<#
.SYNOPSIS
    OpenAI Workshop Infrastructure Deployment Script

.DESCRIPTION
    This script automates the deployment of Azure infrastructure for the OpenAI Workshop.
    It checks prerequisites, initializes Terraform, and deploys the required Azure resources.

.EXAMPLE
    .\deploy.ps1
#>

param()

# Color functions
function Write-Step($message) {
    Write-Host ""
    Write-Host "======================================================================" -ForegroundColor Cyan
    Write-Host $message -ForegroundColor Cyan
    Write-Host "======================================================================" -ForegroundColor Cyan
}

function Write-Success($message) {
    Write-Host "✓ $message" -ForegroundColor Green
}

function Write-Info($message) {
    Write-Host "  $message" -ForegroundColor White
}

function Write-Warning($message) {
    Write-Host "⚠ $message" -ForegroundColor Yellow
}

function Write-ErrorMessage($message) {
    Write-Host "✗ $message" -ForegroundColor Red
}

# Change to script directory
Set-Location $PSScriptRoot

Write-Step "OpenAI Workshop Infrastructure Deployment"

# Step 1: Check prerequisites
Write-Step "Step 1: Checking Prerequisites"

# Check if Azure CLI is installed
try {
    $null = Get-Command az -ErrorAction Stop
    Write-Success "Azure CLI found"
} catch {
    Write-ErrorMessage "Azure CLI is not installed"
    Write-Info "Please install Azure CLI: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli"
    exit 1
}

# Check if Terraform is installed
try {
    $null = Get-Command terraform -ErrorAction Stop
    Write-Success "Terraform found"
} catch {
    Write-ErrorMessage "Terraform is not installed"
    Write-Info "Please install Terraform: https://learn.hashicorp.com/tutorials/terraform/install-cli"
    exit 1
}

# Check if logged in to Azure
try {
    $account = az account show 2>$null | ConvertFrom-Json
    if (-not $account) {
        throw "Not logged in"
    }
    Write-Success "Logged in as: $($account.user.name)"
    Write-Info "Subscription: $($account.name) ($($account.id))"
} catch {
    Write-ErrorMessage "Not logged in to Azure CLI"
    Write-Info "Please run: az login"
    exit 1
}

# Step 2: Setup Terraform variables
Write-Step "Step 2: Setting Up Terraform Variables"

if (-not (Test-Path "terraform.tfvars")) {
    Write-Warning "terraform.tfvars not found, creating from example..."
    Copy-Item "terraform.tfvars.example" "terraform.tfvars"
    Write-Info "Please edit terraform.tfvars with your preferred values"
    Write-Info "Press Enter to continue after editing, or Ctrl+C to exit"
    Read-Host
} else {
    Write-Success "terraform.tfvars found"
}

# Step 3: Initialize Terraform
Write-Step "Step 3: Initializing Terraform"
terraform init
if ($LASTEXITCODE -ne 0) {
    Write-ErrorMessage "Terraform initialization failed"
    exit 1
}
Write-Success "Terraform initialized"

# Step 4: Validate configuration
Write-Step "Step 4: Validating Terraform Configuration"
terraform validate
if ($LASTEXITCODE -ne 0) {
    Write-ErrorMessage "Terraform validation failed"
    exit 1
}
Write-Success "Configuration validated"

# Step 5: Plan deployment
Write-Step "Step 5: Planning Deployment"
terraform plan -out=tfplan
if ($LASTEXITCODE -ne 0) {
    Write-ErrorMessage "Terraform planning failed"
    exit 1
}
Write-Success "Deployment planned"

# Step 6: Apply configuration
Write-Step "Step 6: Applying Configuration"
Write-Warning "This will create Azure resources which may incur costs"
Write-Info "Press Enter to continue, or Ctrl+C to cancel"
Read-Host

terraform apply tfplan
if ($LASTEXITCODE -ne 0) {
    Write-ErrorMessage "Terraform apply failed"
    exit 1
}
Write-Success "Infrastructure deployed successfully!"

# Step 7: Display outputs
Write-Step "Step 7: Deployment Outputs"
terraform output

# Step 8: Generate environment file
Write-Step "Step 8: Generating Environment Configuration"

# Extract key outputs for .env file
$openaiEndpoint = terraform output -raw openai_endpoint
$openaiDeployment = terraform output -raw openai_deployment_name
$aiHubName = terraform output -raw ai_hub_name
$resourceGroup = terraform output -raw resource_group_name

# Create .env template
$envContent = @"
# Generated by Terraform deployment on $(Get-Date)
# Copy these values to your .env file

# Azure OpenAI Configuration
AZURE_OPENAI_ENDPOINT="$openaiEndpoint"
AZURE_OPENAI_CHAT_DEPLOYMENT="$openaiDeployment"
AZURE_OPENAI_API_VERSION="2024-08-01-preview"

# Azure AI Hub
AI_HUB_NAME="$aiHubName"
RESOURCE_GROUP_NAME="$resourceGroup"

# Get your API key from Azure portal:
# AZURE_OPENAI_API_KEY="your-api-key-here"

"@

$envContent | Out-File -FilePath "../workshop.env" -Encoding UTF8

Write-Success "Environment template created: ../workshop.env"
Write-Info "Don't forget to add your Azure OpenAI API key to the .env file"

Write-Step "Deployment Complete!"
Write-Success "Your OpenAI Workshop infrastructure is ready!"
Write-Info "Next steps:"
Write-Info "1. Copy values from workshop.env to your .env file"
Write-Info "2. Get your Azure OpenAI API key from the Azure portal"
Write-Info "3. Visit https://ai.azure.com to create an AI project in your hub"
Write-Info "4. Start building your AI applications!"

Write-Warning "Remember to run 'terraform destroy' when you're done to avoid unnecessary costs"