#!/bin/bash

# OpenAI Workshop Infrastructure Deployment Script
# This script automates the deployment of Azure infrastructure for the OpenAI Workshop

set -e  # Exit on error

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Output functions
print_step() {
    echo -e "\n${BLUE}======================================================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}======================================================================${NC}"
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_info() {
    echo -e "  $1"
}

print_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

# Change to script directory
cd "$(dirname "$0")"

print_step "OpenAI Workshop Infrastructure Deployment"

# Step 1: Check prerequisites
print_step "Step 1: Checking Prerequisites"

# Check if Azure CLI is installed
if ! command -v az &> /dev/null; then
    print_error "Azure CLI is not installed"
    print_info "Please install Azure CLI: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli"
    exit 1
fi
print_success "Azure CLI found"

# Check if Terraform is installed
if ! command -v terraform &> /dev/null; then
    print_error "Terraform is not installed"
    print_info "Please install Terraform: https://learn.hashicorp.com/tutorials/terraform/install-cli"
    exit 1
fi
print_success "Terraform found"

# Check if logged in to Azure
if ! az account show &> /dev/null; then
    print_error "Not logged in to Azure CLI"
    print_info "Please run: az login"
    exit 1
fi

ACCOUNT_INFO=$(az account show)
USER_NAME=$(echo "$ACCOUNT_INFO" | jq -r '.user.name')
SUBSCRIPTION_NAME=$(echo "$ACCOUNT_INFO" | jq -r '.name')
SUBSCRIPTION_ID=$(echo "$ACCOUNT_INFO" | jq -r '.id')

print_success "Logged in as: $USER_NAME"
print_info "Subscription: $SUBSCRIPTION_NAME ($SUBSCRIPTION_ID)"

# Step 2: Setup Terraform variables
print_step "Step 2: Setting Up Terraform Variables"

if [ ! -f "terraform.tfvars" ]; then
    print_warning "terraform.tfvars not found, creating from example..."
    cp terraform.tfvars.example terraform.tfvars
    print_info "Please edit terraform.tfvars with your preferred values"
    print_info "Press Enter to continue after editing, or Ctrl+C to exit"
    read -r
else
    print_success "terraform.tfvars found"
fi

# Step 3: Initialize Terraform
print_step "Step 3: Initializing Terraform"
terraform init
print_success "Terraform initialized"

# Step 4: Validate configuration
print_step "Step 4: Validating Terraform Configuration"
terraform validate
print_success "Configuration validated"

# Step 5: Plan deployment
print_step "Step 5: Planning Deployment"
terraform plan -out=tfplan
print_success "Deployment planned"

# Step 6: Apply configuration
print_step "Step 6: Applying Configuration"
print_warning "This will create Azure resources which may incur costs"
print_info "Press Enter to continue, or Ctrl+C to cancel"
read -r

terraform apply tfplan
print_success "Infrastructure deployed successfully!"

# Step 7: Display outputs
print_step "Step 7: Deployment Outputs"
terraform output

# Step 8: Generate environment file
print_step "Step 8: Generating Environment Configuration"

# Extract key outputs for .env file
OPENAI_ENDPOINT=$(terraform output -raw openai_endpoint)
OPENAI_DEPLOYMENT=$(terraform output -raw openai_deployment_name)
AI_HUB_NAME=$(terraform output -raw ai_hub_name)
RESOURCE_GROUP=$(terraform output -raw resource_group_name)

# Create .env template
cat > ../workshop.env << EOF
# Generated by Terraform deployment on $(date)
# Copy these values to your .env file

# Azure OpenAI Configuration
AZURE_OPENAI_ENDPOINT="$OPENAI_ENDPOINT"
AZURE_OPENAI_CHAT_DEPLOYMENT="$OPENAI_DEPLOYMENT"
AZURE_OPENAI_API_VERSION="2024-08-01-preview"

# Azure AI Hub
AI_HUB_NAME="$AI_HUB_NAME"
RESOURCE_GROUP_NAME="$RESOURCE_GROUP"

# Get your API key from Azure portal:
# AZURE_OPENAI_API_KEY="your-api-key-here"

EOF

print_success "Environment template created: ../workshop.env"
print_info "Don't forget to add your Azure OpenAI API key to the .env file"

print_step "Deployment Complete!"
print_success "Your OpenAI Workshop infrastructure is ready!"
print_info "Next steps:"
print_info "1. Copy values from workshop.env to your .env file"
print_info "2. Get your Azure OpenAI API key from the Azure portal"
print_info "3. Visit https://ai.azure.com to create an AI project in your hub"
print_info "4. Start building your AI applications!"

print_warning "Remember to run 'terraform destroy' when you're done to avoid unnecessary costs"